---
title: "p8105_hw3_cy2752"
author: "Congyu Yang"
date: "2024-10-09"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(p8105.datasets)
data("ny_noaa")
```
## Problem 1
```{r}

```

## Problem 2

```{r}
participant_data <- 
  read_csv("hw3_data/nhanes_covar.csv",skip = 4,col_names = T, na = "NA") %>% 
  janitor::clean_names()%>%
  filter(!is.na(bmi) & !is.na(education)) %>% 
  filter(age >= 21) %>% 
  mutate(sex = as.factor(case_match(sex,1 ~ "male", 2 ~ "female")),
         education = as.factor(case_match(education,
                                1 ~ "Less than high school",
                                2 ~ "High school equivalent",
                                3 ~ "More than high school"))) %>% 
  mutate(sex = factor(sex,levels = c("male","female")),
         education = factor(education,levels = c("Less than high school",
                                       "High school equivalent",
                                       "More than high school")))

accelerometer_data <- 
  read_csv("hw3_data/nhanes_accel.csv")%>% 
  janitor::clean_names()%>%
  pivot_longer(cols = min1:min1440,
               names_to = "min",
               values_to = "mims",
               names_prefix = "min") %>% 
  mutate(min = as.integer(min))

joint_acc_df <- left_join(participant_data,accelerometer_data,by = "seqn")

participant_data %>% 
  janitor::tabyl(education,sex) %>% 
  knitr::kable()
```


```{r}
participant_data %>% 
  ggplot(aes(x = education, y = age,fill = sex))+
  geom_boxplot(alpha = 0.3)
```
*** Missing Comment ***

```{r}
joint_acc_df %>% group_by(seqn,age,sex,education) %>% 
  summarize(total = sum(mims))%>% 
  ggplot(aes(x = age,y = total,color = sex))+
  geom_point(alpha = 0.3)+
  facet_grid(.~education)+
  geom_smooth(se = F)
```
*** Missing Comment ***

```{r fig.width=8, fig.height=6}
joint_acc_df %>% group_by(min,education,sex) %>% 
  summarize(mean_mims = mean(mims)) %>% 
  ggplot(aes(x = min,y = mean_mims,color = sex))+
  geom_point(alpha = 0.3)+
  geom_smooth(se = F)+
  facet_grid(education ~ .)
```

*** Missing Comment ***

## Problem 3

```{r}
citi_jan_2020 <- read_csv("hw3_data/citibike/Jan 2020 Citi.csv") %>% 
  janitor::clean_names()%>%
  mutate(date = "jan_2020",
    rideable_type = as.factor(rideable_type),
         weekdays = as.factor(weekdays),
         member_casual = as.factor(member_casual)) %>% 
  select(date,everything())

citi_jan_2024 <- read_csv("hw3_data/citibike/Jan 2024 Citi.csv") %>% 
  janitor::clean_names()%>%
  mutate(date = "jan_2024",
    rideable_type = as.factor(rideable_type),
         weekdays = as.factor(weekdays),
         member_casual = as.factor(member_casual))%>% 
  select(date,everything())

citi_jul_2020 <- read_csv("hw3_data/citibike/July 2020 Citi.csv") %>% 
  janitor::clean_names()%>%
  mutate(date = "jul_2020",
    rideable_type = as.factor(rideable_type),
         weekdays = as.factor(weekdays),
         member_casual = as.factor(member_casual)) %>% 
  select(date,everything())

citi_jul_2024 <- read_csv("hw3_data/citibike/July 2024 Citi.csv") %>% 
  janitor::clean_names()%>%
  mutate(date = "jul_2024",
    rideable_type = as.factor(rideable_type),
         weekdays = as.factor(weekdays),
         member_casual = as.factor(member_casual))%>% 
  select(date,everything())

citi_all <- bind_rows(citi_jan_2020,citi_jan_2024,citi_jul_2020,
                      citi_jul_2024)
```
*** describe the resulting dataset ***

```{r}
citi_all %>% group_by(date,member_casual) %>% 
  summarize(frcy = n()) %>% 
  pivot_wider(names_from = "member_casual",
              values_from = "frcy") %>% 
  knitr::kable()
```


```{r}
citi_jul_2024 %>% 
  group_by(start_station_name) %>% 
  summarise(frcy = n()) %>% 
  arrange(desc(frcy)) %>% 
  head(5) %>% 
  knitr::kable()
```



```{r}
citi_all %>% separate(date,into = c("month","year"),sep = "_")%>% 
  mutate(weekdays = factor(weekdays,
                           levels = c("Monday","Tuesday","Wednesday",
                              "Thursday","Friday","Saturday","Sunday"))) %>% 
  group_by(year,month,weekdays) %>% 
  summarise(median_duration = median(duration)) %>% 
  ggplot(aes(x = weekdays, y = median_duration,color = year,group = year))+
  geom_point()+ geom_line()+
  facet_grid(.~month,labeller = as_labeller(c("jan" = "January","jul" = "July")))+
  theme(axis.text.x = element_text(size = 8, angle = 45, hjust = 1),
        legend.position = "bottom")
  
```
*** Comment ***

```{r}
citi_all %>% filter(date == "jan_2024" | date == "jul_2024") %>% 
  group_by(date,rideable_type,member_casual) %>% 
  ggplot(aes(x = date,y = duration,fill = rideable_type))+
  geom_boxplot()+
  facet_grid(. ~ member_casual)
```

*** Comment ***